version: "3.11"
services:
  trainer:
    build: .
    command: python src/Pipeline/training_pipeline.py
    volumes:
      - ./artifacts:/app/artifacts


  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./artifacts:/app/artifacts
